<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>smart_nav</name>
  <version>1.0.0</version>
  <description>Navigation stack for Smart Robotics (Nav2)</description>
  <maintainer email="proskurin1408@gmail.com">Oleksandr Proskurin</maintainer>
  <license>GPL-3.0-or-later</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>smart_plugins</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>