import URDFLoader from 'urdf-loader'
import * as ROSLIB from 'roslib'
import * as THREE from 'three'
import { STLLoader } from 'three/addons/loaders/STLLoader.js'

export function createURDFRobot(ros, viewer, tfClient) {
  // 1. Fetch robot_description from get_parameters service
  const paramClient = new ROSLIB.Service({
    ros: ros,
    name: '/robot_state_publisher/get_parameters',
    serviceType: 'rcl_interfaces/srv/GetParameters'
  })

  const request = {
    names: ['robot_description']
  }

  let urdfRobot = null
  let jointSub = null

  paramClient.callService(request, (result) => {
    if (result.values && result.values.length > 0) {
      const urdfString = result.values[0].string_value
      const urdfLoader = new URDFLoader(new THREE.LoadingManager())
      urdfLoader.packages = `http://${window.location.hostname}:8080/packages`
      
      const lightBlueMaterial = new THREE.MeshPhysicalMaterial({
        color: 0x2196f3,          // Lighter blue for chassis
        emissive: 0x051020,
        roughness: 0.5,
        metalness: 0.3,
        clearcoat: 0.2,
        clearcoatRoughness: 0.4,
        reflectivity: 0.7,
        depthWrite: true,
        depthTest: true
      })
      
      const darkBlueMaterial = new THREE.MeshPhysicalMaterial({
        color: 0x1565c0,          // Darker blue for manipulator
        emissive: 0x051020,
        roughness: 0.5,
        metalness: 0.4,
        clearcoat: 0.2,
        clearcoatRoughness: 0.4,
        reflectivity: 0.7,
        depthWrite: true,
        depthTest: true
      })
      
      urdfLoader.loadMeshCb = function (path, manager, material, done) {
        let finalPath = path
        // Intercept absolute file paths generated by xacro and convert to our HTTP server
        if (finalPath.includes('/install/')) {
          const installPart = finalPath.substring(finalPath.indexOf('/install/'))
          finalPath = `http://${window.location.hostname}:8080${installPart}`
        }

        const ext = finalPath.split('.').pop().toLowerCase()
        if (ext === 'stl') {
          const stlLoader = new STLLoader(manager)
          stlLoader.load(
            finalPath,
            (geometry) => {
              geometry.computeVertexNormals()
              
              // Base chassis is light blue, everything else (manipulator/lidar) is dark blue
              const isChassis = finalPath.toLowerCase().includes('base.stl')
              const selectedMaterial = isChassis ? lightBlueMaterial : darkBlueMaterial
              
              const mesh = new THREE.Mesh(geometry, selectedMaterial)
              mesh.castShadow = true
              mesh.receiveShadow = true
              done(mesh)
            },
            undefined,
            (err) => done(null, err)
          )
        } else {
          done(null, new Error('Unsupported mesh format: ' + ext))
        }
      }

      
      urdfRobot = urdfLoader.parse(urdfString)
      
      // Override materials for synchronous primitive shapes (boxes, cylinders in URDF)
      urdfRobot.traverse((child) => {
        if (child.isMesh) {
          child.material = darkBlueMaterial
          child.castShadow = true
          child.receiveShadow = true
        }
      })
      
      viewer.scene.add(urdfRobot)
      console.log('URDF Robot Loaded', urdfRobot)

      // Subscribe to joint states to update the arm with throttle to prevent freezing
      jointSub = new ROSLIB.Topic({
        ros: ros,
        name: '/joint_states',
        messageType: 'sensor_msgs/msg/JointState'
      })

      jointSub.subscribe((msg) => {
        if (!urdfRobot) return
        for (let i = 0; i < msg.name.length; i++) {
          const jointName = msg.name[i]
          const jointAngle = msg.position[i]
          if (urdfRobot.joints[jointName]) {
            urdfRobot.setJointValue(jointName, jointAngle)
          }
        }
      })
      // Dynamically find the root link of the URDF
      let rootLink = 'base_footprint'
      if (urdfRobot.joints && urdfRobot.links) {
        const childLinks = Object.values(urdfRobot.joints).map(j => j.child ? j.child.name : '')
        const allLinks = Object.keys(urdfRobot.links)
        const foundRoot = allLinks.find(l => !childLinks.includes(l))
        if (foundRoot) {
          rootLink = foundRoot
          console.log('Detected URDF Root Link:', rootLink)
        }
      }

      // Link the root of the URDF to its ACTUAL TF frame
      tfClient.subscribe(rootLink, (tf) => {
        urdfRobot.position.set(tf.translation.x, tf.translation.y, tf.translation.z)
        urdfRobot.quaternion.set(tf.rotation.x, tf.rotation.y, tf.rotation.z, tf.rotation.w)
      })

    } else {
      console.error('Failed to get robot_description from robot_state_publisher')
    }
  })
  
  return {
    dispose: () => {
      if (jointSub) jointSub.unsubscribe()
      // tfClient base_footprint unsubscription is handled globally in DigitalTwin3D.vue on disconnect
      
      if (urdfRobot) {
        viewer.scene.remove(urdfRobot)
        
        // Traverse and dispose all geometries and materials to free GPU memory
        urdfRobot.traverse((child) => {
          if (child.isMesh) {
            if (child.geometry) child.geometry.dispose()
            if (child.material) {
              if (Array.isArray(child.material)) {
                child.material.forEach(m => {
                  if (m.map) m.map.dispose()
                  m.dispose()
                })
              } else {
                if (child.material.map) child.material.map.dispose()
                child.material.dispose()
              }
            }
          }
        })
      }
    }
  }
}
